export const GET_LIST_REPORT = "GET_LIST_REPORT"
export const SHOW_PARAMS_REPORT = "SHOW_PARAMS_REPORT"
export const RESET_INFO_PARAMS = "RESET_INFO_PARAMS"
export const UPDATE_INPUT_DATA = "UPDATE_INPUT_DATA"
export const CLICK_CHECK_ROW_REPORT = "CLICK_CHECK_ROW_REPORT"
export const GET_LIST_PARAMS_BY_REPORT = "GET_LIST_PARAMS_BY_REPORT"
export const UPDATE_DATA_CHART = "UPDATE_DATA_CHART"




