export const COMMON_CHECK_CODE_EXISTS = "COMMON_CHECK_CODE_EXISTS"
export const CHANGE_PAGE_TABLE = "CHANGE_PAGE_TABLE"
export const NEXT_PAGE_PRODUCTS = "NEXT_PAGE_PRODUCTS"
export const PREVIOUS_PAGE_PRODUCTS = "PREVIOUS_PAGE_PRODUCTS"
export const UPDATE_INFO_PAGE = "UPDATE_INFO_PAGE"
export const RESET_INFO_PAGE = "RESET_INFO_PAGE"

