const _mapSideToSumm = (side) => {
    return {
        0: 'Handicap',
        1: 'Handicap',
        2: 'Over/Under',
        3: 'Over/Under',
        4: '1X2',
        5: '1X2',
        6: '1X2',
        8: 'Odd/Even',
        9: 'Odd/Even',
        10: 'Outright',
        11: 'Total Goal',
        12: 'Total Goal',
        13: 'Total Goal',
        14: 'Total Goal',
        15: 'Double Chance',
        16: 'Double Chance',
        17: 'Double Chance',
        18: 'Correct Score',
        19: "Correct Score",
        20: "Correct Score",
        21: "Correct Score",
        22: "Correct Score",
        23: "Correct Score",
        24: "Correct Score",
        25: "Correct Score",
        26: "Correct Score",
        27: "Correct Score",
        28: "Correct Score",
        29: "Correct Score",
        30: "Correct Score",
        31: "Correct Score",
        32: "Correct Score",
        33: "Correct Score",
        34: "Correct Score",
        35: "Correct Score",
        36: "Correct Score",
        37: "Correct Score",
        38: "Correct Score",
        39: "Correct Score",
        40: "Correct Score",
        41: "Correct Score",
        42: "Correct Score",
        43: "Correct Score",
        44: 'First Goal/Last Goal',
        45: 'First Goal/Last Goal',
        46: 'First Goal/Last Goal',
        47: 'First Goal/Last Goal',
        48: 'First Goal/Last Goal',
        49: 'HT/FT',
        50: 'HT/FT',
        51: 'HT/FT',
        52: 'HT/FT',
        53: 'HT/FT',
        54: 'HT/FT',
        55: 'HT/FT',
        56: 'HT/FT',
        57: 'HT/FT'
    } [side]
}
module.exports = _mapSideToSumm