export const GET_LIST_USER = 'GET_LIST_USER'
export const GET_LIST_FUNCTION = 'GET_LIST_FUNCTION'
export const GET_LIST_FUNCTION_BY_USER = 'GET_LIST_FUNCTION_BY_USER'
export const UPDATE_LIST_FUNCTION = 'UPDATE_LIST_FUNCTION'


