export const GET_LIST_DATA_USERS = "GET_LIST_DATA_USERS"
export const DELETE_USERS = "DELETE_USERS"
export const ADD_NEW_USERS = "ADD_NEW_USERS"
export const GET_DETAIL_USERS = "GET_DETAIL_USERS"
export const OPEN_MODAL_DETAIL_USERS = "OPEN_MODAL_DETAIL_USERS"
export const UPDATE_INPUT_DATA = "UPDATE_INPUT_DATA"
export const EDIT_ITEM_USERS = "EDIT_ITEM_USERS"
export const CLEAR_DATA_USERS = "CLEAR_DATA_USERS"

