export const CHANGE_INPUT_CONTENT = "CHANGE_INPUT_CONTENT";
export const EDIT_POST = "EDIT_POST";
export const OPEN_CALENDAR = "OPEN_CALENDAR";

export const CONVERT_LIST_CHECK_TYPE = "CONVERT_LIST_CHECK_TYPE";
export const OPEN_MODAL_DETAIL_POST = "OPEN_MODAL_DETAIL_POST";
export const ADD_NEW_POST = "ADD_NEW_POST";

export const CLEAR_DATA_POST = "CLEAR_DATA_POST";
export const INIT_DATA_LISTTYPE = "INIT_DATA_LISTTYPE";
export const CHECKED_LIST_TYPE = "CHECKED_LIST_TYPE";
export const INSERT_TAGS = "INSERT_TAGS";
export const UPDATE_DATEIME_UP = "UPDATE_DATEIME_UP";
export const INSERT_VERSION = "INSERT_VERSION";

export const CHANGE_TAB = "CHANGE_TAB";
export const UPDATE_LIST_CHAPTER = "UPDATE_LIST_CHAPTER";
export const UPDATE_LIST_VIDEO = "UPDATE_LIST_VIDEO";
export const SHOW_MODAL_VIDEOS = "SHOW_MODAL_VIDEOS";
export const UPDATE_INPUT_VIDEO = "UPDATE_INPUT_VIDEO";
export const UPDATE_INPUT_DATA = "UPDATE_INPUT_DATA";
export const CHANGE_STATUS_TOOLBAR = "CHANGE_STATUS_TOOLBAR";
export const GET_LIST_DATA_ARTICLE = "GET_LIST_DATA_ARTICLE";
export const UPDATE_INPUT_CHAPTER = "UPDATE_INPUT_CHAPTER";


