export const GET_LIST_IMAGE = "GET_LIST_IMAGE"
export const UPDATE_SCROLL_LIST = "UPDATE_SCROLL_LIST"
export const LOADING_IMAGE = "LOADING_IMAGE"
export const GET_LIST_BAO_GIA_IN_IMAGE = "GET_LIST_BAO_GIA_IN_IMAGE"
export const UPDATE_CODE_BAOGIA_IMAGE = "UPDATE_CODE_BAOGIA_IMAGE"

