export const CHANGE_INPUT_CONTENT = "CHANGE_INPUT_CONTENT"
export const EDIT_POST = "EDIT_POST"
export const OPEN_CALENDAR = "OPEN_CALENDAR"

export const UPDATE_INPUT_DATA = "UPDATE_INPUT_DATA"

export const CONVERT_LIST_CHECK_TYPE = "CONVERT_LIST_CHECK_TYPE"
export const OPEN_MODAL_DETAIL_POST = "OPEN_MODAL_DETAIL_POST"
export const ADD_NEW_POST = "ADD_NEW_POST"

export const GET_LIST_DATA_POST = "GET_LIST_DATA_POST"
export const CLEAR_DATA_POST = "CLEAR_DATA_POST"
export const INIT_DATA_LISTTYPE = "INIT_DATA_LISTTYPE"
export const CHECKED_LIST_TYPE = "CHECKED_LIST_TYPE"
export const INSERT_TAGS = "INSERT_TAGS"
export const UPDATE_DATEIME_UP = "UPDATE_DATEIME_UP"

