export const GET_OT_LIST_TYPE = 'GET_OT_LIST_TYPE'
export const GET_OT_LIST_ALL = 'GET_OT_LIST_ALL'
export const CHANGE_CODE_TYPE = 'CHANGE_CODE_TYPE'
export const GET_LIST_CONFIG = 'GET_LIST_CONFIG'
export const GET_LIST_DATA_REPORT = 'GET_LIST_DATA_REPORT'
export const GET_LIST_ORDER = 'GET_LIST_ORDER'
export const CHANGE_ORDER_FILTER = 'CHANGE_ORDER_FILTER'

