export const GET_OTHER_PRODUCTS = "GET_OTHER_PRODUCTS"
export const GET_LIST_STONE_BY_PRODUCTS = "GET_LIST_STONE_BY_PRODUCTS"
export const ADD_NEW_ITEM = "ADD_NEW_ITEM"
export const UPDATE_ITEM = "UPDATE_ITEM"
export const DELETE_ITEM_PRODUCTS = "DELETE_ITEM_PRODUCTS"
export const CLICK_ROW_DATA = "CLICK_ROW_DATA"
export const CHECK_ALL_ROW = "CHECK_ALL_ROW"
export const DELETE_ITEM_PRODUCTS_ALL = "DELETE_ITEM_PRODUCTS_ALL"
export const ARRAY_ITEM_TAB_STONE = "ARRAY_ITEM_TAB_STONE"
export const UPDATE_NUMBER_STONE_BY_ID = "UPDATE_NUMBER_STONE_BY_ID"
export const UPDATE_INPUT_DATA = "UPDATE_INPUT_DATA"
export const IS_EDIT = "IS_EDIT"
export const ADD_LIST_STONE = "ADD_LIST_STONE"
export const ADD_LIST_CASTING = "ADD_LIST_CASTING"
export const GET_LIST_CASTING_BY_PRODUCTS = "GET_LIST_CASTING_BY_PRODUCTS"
export const ARRAY_ITEM_TAB_CASTING = "ARRAY_ITEM_TAB_CASTING"
export const UPDATE_ITEM_PRODUCT = "UPDATE_ITEM_PRODUCT"
export const REMOVE_ITEM_CASTING = "REMOVE_ITEM_CASTING"
export const REMOVE_ITEM_STONE = "REMOVE_ITEM_STONE"
export const UPDATE_NUMBER_CASTING_BY_ID = "UPDATE_NUMBER_CASTING_BY_ID"
export const RESET_DATA_PRODUCTS = "RESET_DATA_PRODUCTS"
export const CHANGE_PAGE_TABLE = "CHANGE_PAGE_TABLE"
export const GET_LIST_IMAGE_BY_PRODUCTS = "GET_LIST_IMAGE_BY_PRODUCTS"
export const GET_LIST_MOULD = "GET_LIST_MOULD"
export const ARRAY_ITEM_TAB_MOULD = "ARRAY_ITEM_TAB_MOULD"
export const REMOVE_ITEM_MOULD = "REMOVE_ITEM_MOULD"
export const SELECTED_OPTION = "SELECTED_OPTION"
export const UPDATE_NUMBER_MOULD_BY_ID = "UPDATE_NUMBER_MOULD_BY_ID"
export const GET_LIST_CASTING_IN_PRODUCTS = "GET_LIST_CASTING_IN_PRODUCTS"
export const GET_LIST_STONE_IN_PRODUCTS = "GET_LIST_STONE_IN_PRODUCTS"
export const GET_LIST_ALL_PRODUCTS_COMBOBOX = "GET_LIST_ALL_PRODUCTS_COMBOBOX"
export const ARRAY_ITEM_LIST_PRODUCTS = "ARRAY_ITEM_LIST_PRODUCTS"
export const REMOVE_ITEM_PRODUCTS_SELECTED = "REMOVE_ITEM_PRODUCTS_SELECTED"
export const GENERATE_NUMBER_ID_PRODUCTS = "GENERATE_NUMBER_ID_PRODUCTS"
export const GET_LIST_MOULD_BY_PRODUCTS = "GET_LIST_MOULD_BY_PRODUCTS"
export const GET_LIST_TAB = "GET_LIST_TAB"
export const IS_EDIT_PRODUCT = "IS_EDIT_PRODUCT"
export const GET_DETAIL_BY_PRODUCT = "GET_DETAIL_BY_PRODUCT"
export const NEXT_PAGE_PRODUCTS = "NEXT_PAGE_PRODUCTS"
export const PREVIOUS_PAGE_PRODUCTS = "PREVIOUS_PAGE_PRODUCTS"
export const LOADING_PRODUCTS = "LOADING_PRODUCTS"
export const GET_PRODUCTS_BY_ID = "GET_PRODUCTS_BY_ID"
















