export const GET_LIST_DATA_CHUYENMUC = "GET_LIST_DATA_CHUYENMUC"
export const DELETE_CHUYENMUC = "DELETE_CHUYENMUC"
export const ADD_NEW_CHUYENMUC = "ADD_NEW_CHUYENMUC"
export const GET_DETAIL_CHUYENMUC = "GET_DETAIL_CHUYENMUC"
export const OPEN_MODAL_DETAIL_CHUYENMUC = "OPEN_MODAL_DETAIL_CHUYENMUC"
export const UPDATE_INPUT_DATA = "UPDATE_INPUT_DATA"
export const EDIT_ITEM_LISTTYPE = "EDIT_ITEM_LISTTYPE"
export const CLEAR_DATA_LISTTYPE = "CLEAR_DATA_LISTTYPE"

