export const GET_OTHER_LIST = "GET_OTHER_LIST"
export const ADD_NEW_ITEM = "ADD_NEW_ITEM"
export const UPDATE_ITEM = "UPDATE_ITEM"
export const DELETE_ITEM = "DELETE_ITEM"
export const CLICK_ROW_DATA = "CLICK_ROW_DATA"
export const CHECK_ALL_ROW = "CHECK_ALL_ROW"
export const DELETE_ITEM_ALL = "DELETE_ITEM_ALL"
export const UPDATE_INPUT_DATA = "UPDATE_INPUT_DATA"
export const RESET_DATA_LIST = "RESET_DATA_LIST"
export const CHANGE_PAGE_TABLE = "CHANGE_PAGE_TABLE"
export const GET_COMBOBOX_BY_TYPE = "GET_COMBOBOX_BY_TYPE"

export const UPDATE_FILTER_VALUE_HEADER = "UPDATE_FILTER_VALUE_HEADER"

export const PUSH_LIST_DATA_ALL_DEFAULT = "PUSH_LIST_DATA_ALL_DEFAULT"
export const ADD_LIST_DATA_ALL_DEFAULT = "ADD_LIST_DATA_ALL_DEFAULT"

