// export const LOGIN_REQUEST = 'LOGIN_REQUEST'
// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
// export const LOGIN_FAILURE = 'LOGIN_FAILURE'
// export const LOGIN_PENDING = 'LOGIN_PENDING'
// export const LOGIN_COMPLETE = 'LOGIN_COMPLETE'
// export const LOGIN_RESET = 'LOGIN_RESET'
// export const LOGIN_FORM_CHANGE = 'LOGIN_FORM_CHANGE'
// export const USER_LOGOUT = 'USER_LOGOUT'