export const CHANGE_INPUT_CONTENT = "CHANGE_INPUT_CONTENT"
export const EDIT_POST = "EDIT_POST"
export const OPEN_CALENDAR = "OPEN_CALENDAR"

export const UPDATE_INPUT_DATA = "UPDATE_INPUT_DATA"

export const CONVERT_LIST_CHECK_TYPE = "CONVERT_LIST_CHECK_TYPE"
export const OPEN_MODAL_DETAIL_VIDEO = "OPEN_MODAL_DETAIL_VIDEO"
export const ADD_NEW_VIDEO = "ADD_NEW_VIDEO"

export const GET_LIST_DATA_VIDEO = "GET_LIST_DATA_VIDEO"
export const CLEAR_DATA_VIDEO = "CLEAR_DATA_VIDEO"
export const GET_LIST_DATA_PLAYLIST = "GET_LIST_DATA_PLAYLIST"
export const CONVERT_LIST_PLAY_LIST = "CONVERT_LIST_PLAY_LIST"
export const SHOW_PLAY_LIST = "SHOW_PLAY_LIST"
export const EDIT_VIDEO = "EDIT_VIDEO"
export const UPDATE_THUMBNAIL_VIDEO = "UPDATE_THUMBNAIL_VIDEO"

