export const GET_LIST_DATA_PAGE_SERVICE = "GET_LIST_DATA_PAGE_SERVICE"
export const DELETE_PAGE_SERVICE = "DELETE_PAGE_SERVICE"
export const ADD_NEW_PAGE_SERVICE = "ADD_NEW_PAGE_SERVICE"
export const GET_DETAIL_PAGE_SERVICE = "GET_DETAIL_PAGE_SERVICE"
export const OPEN_MODAL_DETAIL_PAGE_SERVICE = "OPEN_MODAL_DETAIL_PAGE_SERVICE"
export const UPDATE_INPUT_DATA = "UPDATE_INPUT_DATA"
export const EDIT_ITEM_PAGE_SERVICE = "EDIT_ITEM_PAGE_SERVICE"
export const CLEAR_DATA_PAGE_SERVICE = "CLEAR_DATA_PAGE_SERVICE"

