export const GET_OT_LIST_TYPE = 'GET_OT_LIST_TYPE'
export const GET_OT_LIST_ALL = 'GET_OT_LIST_ALL'
export const CHANGE_CODE_TYPE = 'CHANGE_CODE_TYPE'
export const GET_LIST_CONFIG = 'GET_LIST_CONFIG'
export const GET_LIST_FUNCTION_BY_USER = 'GET_LIST_FUNCTION_BY_USER'
export const GET_LIST_FUNCTION = 'GET_LIST_FUNCTION'

